platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!
supports_swift_versions '>= 3.0', '<= 5.4'
source 'https://github.com/CocoaPods/Specs.git'

# Pods for iFlickr
target 'iFlickr' do
    
  #Localizable
  pod 'R.swift', '~> 5.4.0'
  
  #Layout/UI
  pod 'Cartography', '~> 4.0.0'
  pod 'Kingfisher', '~> 6.3.0'

  #Lint
  pod 'SwiftLint', '~> 0.43.1'
  
  # Rx
  pod 'RxSwift', '~> 5.1.2'
  pod 'RxCocoa', '~> 5.1.1'

  #API/Network
  pod 'Moya-ObjectMapper/RxSwift', '~> 2.9'
  
  # Pods for iFlickrTests
  target 'iFlickrTests' do
    inherit! :search_paths
      
    pod 'RxBlocking', '~> 5.1.1'
    pod 'RxTest', '~> 5.1.2'
  end

  # Do some post_install setup
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end